/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -c PageRecordAdaptor -a PageRecordAdaptor.h:PageRecordAdaptor.cpp be.maartenbaert.xml
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef PAGERECORDADAPTOR_H_1448527563
#define PAGERECORDADAPTOR_H_1448527563

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface local.PageRecord
 */
class PageRecordAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "local.PageRecord")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"local.PageRecord\">\n"
"    <method name=\"OnUpdateHotkeyFields\"/>\n"
"    <method name=\"OnUpdateHotkey\"/>\n"
"    <method name=\"OnUpdateSoundNotifications\"/>\n"
"    <method name=\"OnRecordStartPause\"/>\n"
"    <method name=\"OnCancel\"/>\n"
"    <method name=\"OnSave\"/>\n"
"  </interface>\n"
        "")
public:
    PageRecordAdaptor(QObject *parent);
    virtual ~PageRecordAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void OnCancel();
    void OnRecordStartPause();
    void OnSave();
    void OnUpdateHotkey();
    void OnUpdateHotkeyFields();
    void OnUpdateSoundNotifications();
Q_SIGNALS: // SIGNALS
};

#endif
