#!/bin/sh

set -e

cd glinject
echo "Compiling 64-bit GLInject ..."
./compile64
echo "Compiling 32-bit GLInject ..."
./compile32

cd ..
echo "Running pre-build script ..."
./prebuild
echo "Running qmake ..."
qmake
echo "Running make ..."
make -j `grep -c "^processor" /proc/cpuinfo`

echo "Done!"
