#include "StdAfx.h"

// This file was generated by 'x264-preset-translator.php', don't edit it.

void X264Preset(AVCodecContext* cc, const char* preset);

void X264Preset_ultrafast(AVCodecContext* cc);
void X264Preset_superfast(AVCodecContext* cc);
void X264Preset_veryfast(AVCodecContext* cc);
void X264Preset_faster(AVCodecContext* cc);
void X264Preset_fast(AVCodecContext* cc);
void X264Preset_medium(AVCodecContext* cc);
void X264Preset_slow(AVCodecContext* cc);
void X264Preset_slower(AVCodecContext* cc);
void X264Preset_veryslow(AVCodecContext* cc);
void X264Preset_placebo(AVCodecContext* cc);
