.TH SIMPLESCREENRECORDER "1" "March 2015" "SimpleScreenRecorder" "User Commands"
.SH NAME
simplescreenrecorder \- A feature-rich screen recorder that supports X11 and OpenGL.
.SH SYNOPSIS
.B simplescreenrecorder
[\fI\,OPTIONS\/\fR]
.SH DESCRIPTION
SimpleScreenRecorder is a feature-rich screen recorder that supports X11 and
OpenGL. It has a Qt-based graphical user interface. It can record the entire
screen or part of it, or record OpenGL applications directly. The recording
can be paused and resumed at any time. Many different file formats and codecs
are supported.
.SH OPTIONS
.TP
\fB\-\-help\fR
Show help message.
.TP
\fB\-\-logfile\fR
Write log to \fI\,~/.ssr/log\-DATE_TIME.txt\/\fP instead of stdout.
.TP
\fB\-\-statsfile\fR[=\fI\,FILE\/\fR]
Write recording statistics to \fI\,FILE\/\fR. If \fI\,FILE\/\fR is omitted,
\fI\,/dev/shm/simplescreenrecorder\-stats\-PID\/\fP is used. It will
be updated continuously and deleted when the recording
page is closed.
.TP
\fB\-\-syncdiagram\fR
Show synchronization diagram (for debugging).
.TP
\fB\-\-no\-systray\fR
Don't show the system tray icon.
.TP
\fB\-\-start\-hidden\fR
Start the application in hidden form.
.SH "SEE ALSO"
More documentation can be found at
\%http://www.maartenbaert.be/simplescreenrecorder/.
