#!/bin/bash

set -e

usage() {
	echo "Usage: ssr-glinject [OPTIONS] [--] COMMAND"
	echo ""
	echo "Options:"
	echo "  --help              Show this help message."
	echo "  --glx-debug          Enables GLX debugging. This may reduce the performance"
	echo "                       and print lots of error messages, but it is useful to"
	echo "                       track down bugs."
	echo "  --relax-permissions  Uses mode 666 instead of 600 for shared memory, so that"
	echo "                       other users can record the stream. This is insecure and"
	echo "                       should not be used on a computer that can be accessed by"
	echo "                       other users that you don't trust."
	echo ""
	echo "This script uses LD_PRELOAD to inject the GLInject library into the given"
	echo "command, so that SimpleScreenRecorder can record it. It should be safe to use"
	echo "this on all applications (including command-line programs and shell scripts)."
	echo "If the program doesn't use OpenGL, it should have no effect. If you find a"
	echo "program that crashes or behaves incorrectly when GLInject is used, please submit"
	echo "a bug report."
}

export SSR_GLX_DEBUG=0
export SSR_STREAM_RELAX_PERMISSIONS=0

while [ $# -gt 0 ]
do
	if [ x"$1" = x"--" ]
	then
		shift
		break
	elif [ x"$1" = x"--help" ]
	then
		usage
		exit
	elif [ x"$1" = x"--glx-debug" ]
	then
		export SSR_GLX_DEBUG=1
		shift
	elif [ x"$1" = x"--relax-permissions" ]
	then
		export SSR_STREAM_RELAX_PERMISSIONS=1
		shift
	elif [ x"${1:0:1}" = x"-" ]
	then
		echo "ssr-glinject: Unknown option '$1'!" >& 2
		usage
		exit 1
	else
		break
	fi
done

LD_PRELOAD="libssr-glinject.so $LD_PRELOAD" "$@"
