
#rules for finding library XExtensions
find_path(XEXTENSIONS_INCLUDE_DIR X11/extensions/Xfixes.h)
find_library(XFIXES_LIBRARY NAMES Xfixes)
find_library(XEXT_LIBRARY NAMES Xext)
find_library(XI_LIBRARY NAMES Xi)

set(XEXTENSIONS_LIBRARIES ${XFIXES_LIBRARY} ${XEXT_LIBRARY} ${XI_LIBRARY})
set(XEXTENSIONS_INCLUDE_DIRS ${XEXTENSIONS_INCLUDE_DIR} )

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(XExtensions DEFAULT_MSG XFIXES_LIBRARY XEXT_LIBRARY XI_LIBRARY XEXTENSIONS_INCLUDE_DIR)

mark_as_advanced(XEXTENSIONS_INCLUDE_DIR XFIXES_LIBRARY XEXT_LIBRARY XI_LIBRARY)
