%YAML 1.1
---
# Snapcraft Recipe for SimpleScreenRecorder
# ------------------------------
# This file is in the YAML data serialization format:
# http://yaml.org
# For the spec. of writing this file refer the following documentation:
# * The snapcraft format
#   https://docs.snapcraft.io/the-snapcraft-format/8337
# * Snap Documentation
#   https://docs.snapcraft.io
# * Topics under the doc category in the Snapcraft Forum
#   https://forum.snapcraft.io/c/doc
# For support refer to the snapcraft section in the Snapcraft Forum:
# https://forum.snapcraft.io/c/snapcraft
name: simplescreenrecorder
title: SimpleScreenRecorder
summary: A feature-rich screen recorder
description: |
  SimpleScreenRecorder is a feature-rich screen recorder that supports
  X11 and OpenGL. It has a Qt-based graphical user interface. It can
  record the entire screen or part of it, or record OpenGL applications
  directly(currently not supported in the snap distribution). The recording
  can be paused and resumed at any time. Many different file formats and
  codecs are supported.

  **Key features**

  * Synchronizes audio and video properly.
  * Reduces the video frame rate if your computer is too slow.
  * Fully multithreaded: small delays in any of the components will
    never block the other components, resulting is smoother video and
    better performance on computers with multiple processors.
  * Can also do live streaming (experimental).

  **Known issues**

  Currently OpenGL recording is not supported by this build due to the
  confinement and library separation nature of snap apps.

icon: data/icons/scalable/simplescreenrecorder.svg
license: GPL-3.0
#version: determined-by-adopt-info

adopt-info: main
base: core18
confinement: strict
grade: stable

parts:
  # Files to patch the files in the snap
  patching:
    source: snap/local/patching
    plugin: dump
    organize:
      '*': patching/
    prime:
    - -*

  # Launcher programs to fix problems at runtime
  launchers:
    source: snap/local/launchers
    plugin: dump
    organize:
      '*': bin/

  # Scriptlet to only build latest tagged release software if it hasn't
  # been promoted to the stable channel
  # https://forum.snapcraft.io/t/the-selective-pull-scriptlet-stage-snap-workaround/10389
  selective-pull:
    plugin: nil
    build-packages:
    - git
    stage-snaps:
    - selective-pull

  # Remote part for support of various desktop technologies
  # Refer: https://github.com/ubuntu/snapcraft-desktop-helpers/blob/master/snapcraft.yaml
  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-depth: 1
    source-subdir: qt

    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
    - build-essential
    - qtbase5-dev
    - dpkg-dev
    stage-packages:
    - libxkbcommon0
    - ttf-ubuntu-font-family
    - dmz-cursor-theme
    - light-themes
    - adwaita-icon-theme
    - gnome-themes-standard
    - shared-mime-info
    - libqt5gui5
    - libgdk-pixbuf2.0-0
    - libqt5svg5 # for loading icon themes which are svg
    - try: [appmenu-qt5] # not available on core18
    - locales-all
    - xdg-user-dirs
    - fcitx-frontend-qt5

  main:
    after:
    # for patch-desktop-entries.*
    - patching

    # for selective-pull scriptlet
    - selective-pull

    source: .

    # For building stable releases when needed
    #source-tag: 0.3.11

    override-pull: |
      set -o nounset
      "${SNAPCRAFT_STAGE}"/scriptlets/selective-pull

    plugin: cmake
    configflags:
    # Fix output profiles and localization data access
    - -DCMAKE_INSTALL_DATAROOTDIR=/snap/$SNAPCRAFT_PROJECT_NAME/current/share

    # Disable OpenGL recording support as it's not possible due to the confined nature of snaps and also for non i386/AMD64 architecture build from source compatibility
    - -DWITH_OPENGL_RECORDING=FALSE
    - -DWITH_GLINJECT=FALSE

    - -DWITH_QT5=TRUE
    build-packages:
    - libasound2-dev
    - libavcodec-dev
    - libavformat-dev
    - libavutil-dev
    - libjack-dev
    - libpulse-dev
    - libqt5x11extras5-dev
    - libswscale-dev
    - libxi-dev
    - libxinerama-dev
    - pkg-config
    - qt5-default
    - qt5-qmake
    - qtbase5-dev
    - qttools5-dev-tools
    stage-packages:
    # Used in button and menu entries
    - breeze-icon-theme

    - libasound2
    #- libavcodec57
    - libavcodec-extra57
    - libavformat57
    - libavutil55
    - libjack0
    - libpulse0
    - libqt5x11extras5
    - libswscale4
    - libxi6
    - libxinerama1

    # gtk-common-themes support
    - qt5-gtk-platformtheme

    organize:
      snap/$SNAPCRAFT_PROJECT_NAME/current: /
    stage:
    # Drop remnants from organizing
    - -snap
    override-prime: |
      set \
        -o nounset

      snapcraftctl prime

      "${SNAPCRAFT_STAGE}"/patching/patch-desktop-entries.bash

    # Avoid using description from appdata until custom override is supported
    # Bug #1820797 “Snapcraft should allow prepending/appending additional text from description extracted from adopt-info” : Bugs : Snapcraft
    # https://bugs.launchpad.net/snapcraft/+bug/1820797
    parse-info:
    - share/appdata/simplescreenrecorder.appdata.xml

apps:
  simplescreenrecorder:
    adapter: full
    command: bin/simplescreenrecorder
    command-chain:
    - bin/desktop-launch
    - bin/simplescreenrecorder-launch

    common-id: simplescreenrecorder.desktop
    desktop: share/applications/simplescreenrecorder.desktop
    #environment:
      # gtk-common-themes support
      # DISABLED: Got overrided by desktop-launch(`appmenu-qt5`), implement in snap launcher instead
      #QT_QPA_PLATFORMTHEME: gtk3

plugs:
  # Audio access
  alsa: # Non-A/C
  pulseaudio:

  # For snaps with a graphical user interface:
  desktop:
  desktop-legacy:
  x11:
  unity7:
  wayland:

  # To allow wayland apps access system theme settings
  gsettings:

  # gtk-common-themes support
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes:gtk-3-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes:icon-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes:sounds-themes

  # T.B.D.
  opengl:

  # Storage access
  home:
  removable-media: # Non-A/C

  # Network access (livestreaming support?)
  network:

layout:
  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa
  /usr/share/X11/locale:
    bind: $SNAP/usr/share/X11/locale
